# encoding: utf-8
# ---------------------------------------------------------------------------
# Workbench inspection journal — GENERATED by cfdauto (`python main.py wb-info`).
# Dumps systems, components and parameters to JSON so the user can fill in
# workbench.system_name / workbench.aoa_parameter without guessing.
# IronPython 2.7 compatible.
# ---------------------------------------------------------------------------
import json
import traceback

INFO = {"success": False, "systems": [], "parameters": [], "error": None}

try:
    Open(FilePath=r"$PROJECT_PATH")

    for system in GetAllSystems():
        entry = {"name": "?", "display_text": "?", "components": []}
        try:
            entry["name"] = str(system.Name)
        except Exception:
            pass
        try:
            entry["display_text"] = str(system.DisplayText)
        except Exception:
            pass
        try:
            for comp in system.Components:
                try:
                    entry["components"].append(str(comp.Name))
                except Exception:
                    pass
        except Exception:
            pass
        INFO["systems"].append(entry)

    try:
        for p in Parameters.GetAllParameters():
            record = {"name": "?", "display_text": "?", "value": "?", "usage": "?"}
            try:
                record["name"] = str(p.Name)
            except Exception:
                pass
            try:
                record["display_text"] = str(p.DisplayText)
            except Exception:
                pass
            try:
                record["value"] = str(p.Value)
            except Exception:
                pass
            try:
                record["usage"] = str(p.Usage)   # Input / Output
            except Exception:
                pass
            INFO["parameters"].append(record)
    except Exception:
        pass

    INFO["success"] = True

except Exception as err:
    INFO["error"] = "%s\n%s" % (str(err), traceback.format_exc())

f = open(r"$STATUS_JSON", "w")
try:
    f.write(json.dumps(INFO, indent=2))
finally:
    f.close()
