# encoding: utf-8
# ---------------------------------------------------------------------------
# Workbench batch journal — GENERATED by cfdauto, do not edit the rendered copy.
#
# IMPORTANT: Workbench journals run under IronPython 2.7. Keep this file free
# of Python-3-only syntax (no f-strings, no pathlib, no print()-with-kwargs).
#
# Placeholders (dollar-NAME) are substituted by cfdauto.workbench_controller using
# string.Template, which is why literal { } braces below are safe.
# ---------------------------------------------------------------------------
import json
import traceback

STATUS = {
    "success": False,
    "stage": "start",
    "messages": [],
    "error": None,
    "parameters": {},
}


def note(msg):
    STATUS["messages"].append(str(msg))


def dump_status():
    f = open(r"$STATUS_JSON", "w")
    try:
        f.write(json.dumps(STATUS, indent=2))
    finally:
        f.close()


try:
    # ---------------------------------------------------------------- open
    STATUS["stage"] = "open_project"
    Open(FilePath=r"$PROJECT_PATH")
    note("Project opened: $PROJECT_PATH")

    # ------------------------------------------------------ set parameters
    STATUS["stage"] = "set_parameters"
    requested = json.loads(r'''$PARAMS_JSON''')

    def find_parameter(name):
        # 1) exact internal name (P1, P2, ...); 2) display text ("AOA").
        try:
            return Parameters.GetParameter(Name=name)
        except Exception:
            pass
        try:
            for cand in Parameters.GetAllParameters():
                try:
                    if cand.DisplayText == name or cand.Name == name:
                        return cand
                except Exception:
                    continue
        except Exception:
            pass
        return None

    for pname in sorted(requested.keys()):
        expr = requested[pname]
        target = find_parameter(pname)
        if target is None:
            raise Exception(
                "Workbench parameter '%s' not found. Run 'python main.py wb-info' "
                "to list available parameters." % pname
            )
        target.Expression = expr
        note("Parameter %s set to %s" % (pname, expr))

    # Snapshot every parameter value for traceability.
    try:
        for p in Parameters.GetAllParameters():
            try:
                STATUS["parameters"][str(p.Name)] = str(p.Value)
            except Exception:
                STATUS["parameters"][str(p.Name)] = "<unreadable>"
    except Exception:
        note("Could not enumerate parameters for the snapshot (non-fatal).")

    # -------------------------------------------------- update the systems
    system1 = GetSystem(Name="$SYSTEM_NAME")

    if $UPDATE_GEOMETRY:
        STATUS["stage"] = "update_geometry"
        geometry = system1.GetComponent(Name="Geometry")
        geometry.Update(AllDependencies=True)
        note("Geometry component updated")

    STATUS["stage"] = "update_mesh"
    mesh = system1.GetComponent(Name="Mesh")
    mesh.Update(AllDependencies=True)
    note("Mesh component updated")

    if $REFRESH_SETUP:
        # Refreshing the Setup cell makes Workbench write the Fluent transfer
        # mesh (FFF.msh / .msh.h5) into dp0/<sys>/MESH so the orchestrator can
        # pick it up.  It briefly starts a headless Fluent to import the mesh;
        # a failure here is tolerated because on many versions the mesh file
        # already exists after the Mesh update above.
        STATUS["stage"] = "refresh_setup"
        try:
            setup = system1.GetComponent(Name="Setup")
            setup.Refresh()
            note("Setup component refreshed (mesh transferred to Fluent format)")
        except Exception as refresh_err:
            note("Setup refresh failed (non-fatal): %s" % str(refresh_err))

    if $SAVE_PROJECT:
        STATUS["stage"] = "save_project"
        Save(Overwrite=True)
        note("Project saved")

    STATUS["stage"] = "done"
    STATUS["success"] = True

except Exception as err:
    STATUS["error"] = "%s\n%s" % (str(err), traceback.format_exc())

dump_status()
