"""Project scaffolding — turn a chosen template into a runnable project
(Capability 3).

``cfdauto.project_manager`` deliberately owns *only* the project folder shape
and its ``project.json`` metadata, with no engine/openpyxl imports. This
module is the counterpart that does the template-aware generation: given a
project root and a :class:`SimulationTemplate` id, it writes

* ``data/experiments.xlsx`` — the schedule workbook for **that template's**
  study (input columns + example sweep), via the already template-agnostic
  :func:`tools.make_experiment_template.build_template`; and
* ``config/config.yaml`` — a minimal, immediately-loadable config that records
  ``runtime.template`` (so the engine, I/O, and UI all resolve the project's
  template) and points at the generated workbook and the project's ``runs/``.

The result is a project that opens and runs with no hand-editing — "New
Project → choose template → workbook + study + strategy → ready".
"""

from __future__ import annotations

from pathlib import Path

import yaml

from .experiment_definition import ExperimentDefinition
from .simulation_context import SimulationContext


def scaffold_project(root, template_id: str = "", *, mock: bool = True) -> Path:
    """Generate ``config/config.yaml`` + ``data/experiments.xlsx`` for a
    project's chosen template. Returns the config path.

    ``template_id`` is resolved through the registry (empty → the default);
    the *resolved* id is written to ``runtime.template`` so the choice is
    explicit and self-describing. ``mock=True`` (default) makes a fresh project
    immediately runnable without ANSYS — the sane starting point for a new
    study; the user turns it off once a real baseline case is configured.
    """
    root = Path(root)
    context = SimulationContext.for_template_id(template_id)
    exp_def = ExperimentDefinition.from_context(context)

    # Workbook for this template's study (template-agnostic generator).
    from tools.make_experiment_template import build_template
    data_dir = root / "data"
    data_dir.mkdir(parents=True, exist_ok=True)
    xlsx = data_dir / "experiments.xlsx"
    build_template(xlsx, exp_def=exp_def)

    # Minimal, self-contained config. Absolute paths so it loads regardless of
    # the working directory the app happens to run from.
    cfg_dir = root / "config"
    cfg_dir.mkdir(parents=True, exist_ok=True)
    cfg_path = cfg_dir / "config.yaml"
    config_doc = {
        "excel": {"file": str(xlsx.resolve())},
        "runtime": {
            "work_dir": str((root / "runs").resolve()),
            "template": context.template.id,
            "mock": bool(mock),
            "study_name": root.name,
        },
    }
    cfg_path.write_text(
        "# Generated by Slipstream — project template: "
        f"{context.template.name} ({context.template.id})\n"
        + yaml.safe_dump(config_doc, sort_keys=False),
        encoding="utf-8")
    return cfg_path
